### ISSUE TITLE
Unique addresses across EVMs

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-core-contracts#102]

**Comment by tbwebb22** [comment]
This issue was solved when we updated the factory contracts to use the create2 pattern

**Comment by adamgall** [comment]
@tbwebb22 

Was this issue regarding:

- making sure that DAOs _didn't_ share addresses across networks (which is fixed now), or
- making sure that Factory contracts _do_ share the same address across networks (which I think is just a manual process now)

**Comment by tbwebb22** [comment]
Pretty sure this was in regards to the first one, since this issue was opened right before we started the work on adding create2 to all the factories.
