### ISSUE TITLE
Gnosis Safe based Fractal Node - first steps

### ISSUE THREAD

**Issue by herbig** [decent-dao/fractal-core-contracts#123]
We'd like to build the first steps towards a Gnosis Safe based Fractal node (as outlined in https://www.notion.so/hulking-cosmos-3e8/Gnosis-Based-Fractal-DAO-Nodes-a865c68b3dcb4095bdc8ae8167aab624).

This first step is a contract that can deploy a new Gnosis Safe (representing a Fractal DOA), and attach a module to it, in a single transaction.

This will then allow the front end to begin speccing out working with Gnosis Safes in the front end UI.

- [ ] A contract with the ability to deploy a new Gnosis Safe and attach a module in a single transaction. This would be something similar to `createDAO` with `CreateDAOParams`.

**Comment by adamgall** [comment]
i believe this issue should live in the `fractal-module-gnosis` repo https://github.com/decent-dao/fractal-module-gnosis

**Comment by herbig** [comment]
Closed in favor of https://github.com/decent-dao/fractal-module-gnosis/issues/18
