### ISSUE TITLE
Immunefi Bug Bounty Program

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-core-contracts#71]
Document / template provided by Immunefi: https://docs.google.com/document/d/12uL3GArO8muomzrYldEFZYu8Q8QO2j11kw7K9K_i08U/edit?pli=1

directive:
- help fill out / edit / provide relevant bullet points on end of page 2 into page 3
- give insightful answers to other questions (for example, we definitely don't need to require that bug reporters suggest fixes -- we are very technical, we'll know how to best fix a bug if one is found)

**Comment by dannydecent** [comment]
Chris will be spinning up a verified DAO for the smart contract to add to the verified scope table for the bug bounty.
All three contracts - doc list here: https://docs.google.com/spreadsheets/d/1YHIMlGDJ8CWJaHOJKm6i1fDg-2Ot85aCNQkOuZeT5ik/edit#gid=0
