### ISSUE TITLE
Should DAO inherit from ModuleBase?

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-core-contracts#81]
The module factories are maintaining the versions of the modules, so the modules need to know which factory they were deployed from.

However, in this case of the DAO contract, it doesn't really make sense, since the DAO Factory doesn't inherit from ModuleFactoryBase. So maybe we should rethink the DAO inheriting from ModuleBase, or figure out if the DAO factory can inherit from ModuleFactoryBase.

__Originally posted by @tbwebb22 in https://github.com/decent-dao/fractal-contracts/pull/80#discussion_r881011047__

**Comment by tbwebb22** [comment]
Yes, this can be closed. We've discussed this one a few times and Chris and I agreed it does make sense for the DAO to inherit from module base, as it still does make sense to keep track of the DAO factory address that deployed the DAO. Also, it needs the authorized modifier.
