### ISSUE TITLE
Replace "AccessControl" with "Ownable" in `ModuleFactoryBase`

### ISSUE THREAD

**Issue by adamgall** [decent-dao/fractal-core-contracts#93]
Is there an explicit reason why OZ's `AccessControl` is used in here, instead of the simpler `Ownable`? I ask because I only see one role that's being used. So why not just make it Ownable (which is also, effectively, "one role").

**Comment by tbwebb22** [comment]
Yes, I believe that is the only functional difference between the two. 

This brings up the question, do we actually want more than one address to be able to call the `addVersion` function.

While it may not be necessary, we (and module developers) may find this extra flexibility to be useful in the future.

**Comment by adamgall** [comment]
Yeah, we can leave it as is 👍
